-- Criar 100 usuários bots com nomes brasileiros
INSERT INTO public.profiles (user_id, full_name, email, is_bot, is_admin, bids_balance) VALUES
(gen_random_uuid(), 'João Silva', 'joao.silva.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Maria Santos', 'maria.santos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Pedro Oliveira', 'pedro.oliveira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Ana Costa', 'ana.costa.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Carlos Souza', 'carlos.souza.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Fernanda Lima', 'fernanda.lima.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Ricardo Almeida', 'ricardo.almeida.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Juliana Pereira', 'juliana.pereira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Bruno Rodrigues', 'bruno.rodrigues.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Camila Ferreira', 'camila.ferreira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Lucas Martins', 'lucas.martins.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Beatriz Ribeiro', 'beatriz.ribeiro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Felipe Carvalho', 'felipe.carvalho.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Mariana Gomes', 'mariana.gomes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Diego Barbosa', 'diego.barbosa.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Larissa Dias', 'larissa.dias.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Thiago Nascimento', 'thiago.nascimento.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Gabriela Rocha', 'gabriela.rocha.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Rafael Moreira', 'rafael.moreira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Isabella Torres', 'isabella.torres.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'André Cardoso', 'andre.cardoso.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Vitória Campos', 'vitoria.campos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Gustavo Correia', 'gustavo.correia.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Sophia Araújo', 'sophia.araujo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Leonardo Teixeira', 'leonardo.teixeira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Nicole Reis', 'nicole.reis.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Matheus Freitas', 'matheus.freitas.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Yasmin Castro', 'yasmin.castro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Caio Pinto', 'caio.pinto.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Letícia Vieira', 'leticia.vieira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Daniel Nogueira', 'daniel.nogueira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Melissa Duarte', 'melissa.duarte.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Gabriel Monteiro', 'gabriel.monteiro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Amanda Borges', 'amanda.borges.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'João Pedro Machado', 'joao.pedro.machado.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Emanuelle Farias', 'emanuelle.farias.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Renan Cavalcanti', 'renan.cavalcanti.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Bruna Mendes', 'bruna.mendes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Victor Hugo Lopes', 'victor.hugo.lopes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Isabelle Azevedo', 'isabelle.azevedo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Guilherme Nunes', 'guilherme.nunes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Luana Moura', 'luana.moura.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Enzo Miranda', 'enzo.miranda.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Giovanna Cunha', 'giovanna.cunha.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Arthur Medeiros', 'arthur.medeiros.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Eduarda Batista', 'eduarda.batista.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Davi Santana', 'davi.santana.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Alice Guimarães', 'alice.guimaraes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Samuel Ramos', 'samuel.ramos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Helena Soares', 'helena.soares.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Nathan Peixoto', 'nathan.peixoto.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Marina Coelho', 'marina.coelho.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Bernardo Melo', 'bernardo.melo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Júlia Tavares', 'julia.tavares.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Ian Cordeiro', 'ian.cordeiro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Cecília Barros', 'cecilia.barros.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Lorenzo Magalhães', 'lorenzo.magalhaes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Pietra Vasconcelos', 'pietra.vasconcelos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Miguel Guerreiro', 'miguel.guerreiro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Agatha Porto', 'agatha.porto.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Heitor Siqueira', 'heitor.siqueira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Sarah Moraes', 'sarah.moraes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Cauã Brandão', 'caua.brandao.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Esther Galvão', 'esther.galvao.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Noah Evangelista', 'noah.evangelista.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Antonella Fonseca', 'antonella.fonseca.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Theo Paiva', 'theo.paiva.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Rafaela Macedo', 'rafaela.macedo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Benjamin Leite', 'benjamin.leite.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Milena Xavier', 'milena.xavier.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Pedro Henrique Figueiredo', 'pedro.henrique.figueiredo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Sophie Miranda', 'sophie.miranda.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'João Vitor Andrade', 'joao.vitor.andrade.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Valentina Matos', 'valentina.matos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Davi Lucca Campos', 'davi.lucca.campos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Maya Brito', 'maya.brito.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Joaquim Esteves', 'joaquim.esteves.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Luna Carmo', 'luna.carmo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Benício Aguiar', 'benicio.aguiar.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Catarina Passos', 'catarina.passos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Eduardo Silva', 'eduardo.silva.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Clarice Mendonça', 'clarice.mendonca.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Felipe Augusto Torres', 'felipe.augusto.torres.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Antonella Costa', 'antonella.costa.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'João Miguel Santos', 'joao.miguel.santos.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Maitê Ferreira', 'maite.ferreira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Anthony Gabriel Souza', 'anthony.gabriel.souza.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Lavínia Alves', 'lavinia.alves.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Arthur Gabriel Lima', 'arthur.gabriel.lima.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Isis Oliveira', 'isis.oliveira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Lucca Ribeiro', 'lucca.ribeiro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Stella Barbosa', 'stella.barbosa.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'João Gabriel Martins', 'joao.gabriel.martins.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Olívia Cardoso', 'olivia.cardoso.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Murilo Rocha', 'murilo.rocha.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Alícia Nascimento', 'alicia.nascimento.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Pietro Gomes', 'pietro.gomes.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Mel Dias', 'mel.dias.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'João Lucas Pereira', 'joao.lucas.pereira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Jade Correia', 'jade.correia.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Gael Araújo', 'gael.araujo.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Malu Monteiro', 'malu.monteiro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Ravi Carvalho', 'ravi.carvalho.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Aurora Teixeira', 'aurora.teixeira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Henry Castro', 'henry.castro.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Heloísa Reis', 'heloisa.reis.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Lorenzo Gabriel Vieira', 'lorenzo.gabriel.vieira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Manuela Freitas', 'manuela.freitas.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Davi Miguel Pinto', 'davi.miguel.pinto.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Ayla Nogueira', 'ayla.nogueira.bot@leilao.com', true, false, 999999999),
(gen_random_uuid(), 'Noah Miguel Duarte', 'noah.miguel.duarte.bot@leilao.com', true, false, 999999999);