-- Inserir alguns leilões ativos para teste
INSERT INTO public.auctions (
  title, 
  description, 
  image_url, 
  current_price, 
  starting_price, 
  market_value, 
  bid_increment, 
  bid_cost, 
  time_left, 
  ends_at, 
  status, 
  protected_mode, 
  protected_target
) VALUES 
  (
    'iPhone 15 Pro Max', 
    'Novo iPhone 15 Pro Max 256GB Titânio Natural',
    '/lovable-uploads/256b9754-1234-4f7d-9aa0-2ef9e0a089bd.png',
    150, 
    100, 
    8999, 
    1, 
    75, 
    15, 
    NOW() + INTERVAL '30 minutes',
    'active',
    true,
    1500
  ),
  (
    'MacBook Air M3', 
    'MacBook Air 13" com chip M3 e 16GB de RAM',
    '/src/assets/macbook-air-m2.jpg',
    280, 
    200, 
    12999, 
    2, 
    100, 
    15, 
    NOW() + INTERVAL '45 minutes',
    'active',
    false,
    0
  ),
  (
    'PlayStation 5 Pro', 
    'Console PlayStation 5 Pro com SSD de 2TB',
    '/src/assets/playstation-5.jpg',
    420, 
    350, 
    4999, 
    3, 
    80, 
    15, 
    NOW() + INTERVAL '1 hour',
    'active',
    true,
    2000
  );